Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
VMHOSTNAME="minion1"
VMIP="192.168.100.100"

Vagrant.configure (VAGRANTFILE_API_VERSION) do | config |
    config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = VMHOSTNAME
	# network setting
    config.vm.network :private_network, ip: VMIP

    config.vm.provider :virtualbox do | vb |
        vb.name = VMHOSTNAME
        vb.gui = false
        vb.cpus = 1
        vb.memory = 512
     end
end
