version: '2'

services:
  proxy:
    image: nginx
    ports:
      - '80:80'
    links:
        - petclinic:petclinic
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf        
  petclinic:
    build:
      context: .
      dockerfile: petclinic.Dockerfile
    links: 
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
  
