# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "master" do |cfg|
	cfg.vm.box = "ubuntu/bionic64"
	cfg.vm.network "private_network", ip: "192.168.100.100"
	cfg.vm.host_name = "master"
	cfg.vm.provider "virtualbox" do |vb|
	  vb.memory = "4096"
	end
  end

  config.vm.define "node1" do |cfg|
	cfg.vm.box = "ubuntu/bionic64"
	cfg.vm.network "private_network", ip: "192.168.100.101"
	cfg.vm.host_name = "node1"
	cfg.vm.provider "virtualbox" do |vb|
	  vb.memory = "2048"
	end
  end

  config.vm.define "node2" do |cfg|
	cfg.vm.box = "ubuntu/bionic64"
	cfg.vm.network "private_network", ip: "192.168.100.102"
	cfg.vm.host_name = "node1"
	cfg.vm.provider "virtualbox" do |vb|
	  vb.memory = "2048"
	end
  end

  config.vm.define "node3" do |cfg|
	cfg.vm.box = "ubuntu/bionic64"
	cfg.vm.network "private_network", ip: "192.168.100.103"
	cfg.vm.host_name = "node1"
	cfg.vm.provider "virtualbox" do |vb|
	  vb.memory = "2048"
	end
  end

end

