web:
    image: nginx
    ports:
        - "80:80"
    links:
        - petclinic:petclinic
        - petclinic2:petclinic2
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
web2:
    image: nginx
    ports:
        - "90:80"
    links:
        - petclinic:petclinic
        - petclinic2:petclinic2
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
petclinic:
    image: tomcat
    ports:
        - "8080"
    links:
        - db
    volumes:
        - ./files/petclinic.war:/usr/local/tomcat/webapps/petclinic.war
petclinic2:
    image: tomcat
    ports:
        - "8080"
    links:
        - db
    volumes:
        - ./files/petclinic.war:/usr/local/tomcat/webapps/petclinic.war
db:
    image: mariadb
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: petclinic
        MYSQL_DATABASE: petclinic
